### ISSUE TITLE
Suggestion: Make it so you can use the copy paste features if you're a regular user.

### ISSUE THREAD

**Issue by JadeiteWren** [MisterIXI/fvtt-copy-id#1] opened 2022-04-13 06:41 UTC
Since players can't move actor tokens, having them be able to copy pages to list in their journals or bios would be highly appreciated.

**Comment by MisterIXI** [comment] 2022-04-13 08:37
I didn't even know that players couldn't drag and drop their own actor.
Since the change is fairly simple I addressed it in #2. 
Let me know if that helps your case.

**Comment by JadeiteWren** [comment] 2022-04-13 11:23
Yea, since if you don't have create token perms, you can't drag and drop any tokens. So you have to type out links or get the DM to make it for you.
It caused a problem for trying to explain to people how to make links to their friends pages, journals, etc.

Thank you! I'll update you when I'm able fo check that out and see if they can use the copy paste feature!

**Comment by JadeiteWren** [comment] 2022-04-13 22:32
Okay so, tested it finally. The button is there on actor pages for my players, but clicking it does not copy the ID.

For me, the GM, the button does copy the ID still.

This is what console is telling me when I press the copy button for players.
> copyID.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
> [Detected 1 package: fvtt-copy-id]
>     at Object.onclick (copyID.js:11:41)
>     at HTMLAnchorElement.<anonymous> (foundry.js:3203:16)
>     at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
>     at HTMLAnchorElement.v.handle (jquery.min.js:2:41048)

**Comment by MisterIXI** [comment] 2022-04-13 22:58
Huh, interesting. If I understand correctly the problem ist when you're not using SSL/Https. I had it enabled so my tests all worked.  
Due to security the browser blocks this operation when on a "unsecure" Site.
It probably only worked for you because you used foundry directly. Accessed via localhost also blocked it for me.  
I will see if I find a way around this problem, but in the meantime you could also [enable https](https://foundryvtt.com/article/ssl/) as a workaround.

**Comment by MisterIXI** [comment] 2022-04-14 00:21
So the issue can't be fixed in a clean way as far as I could find. The only usable (and kind of dirty) trick is deprecated by now.  
I added a fallback though which is just slightly inconvenient with a prompt popup. Actually enabling HTTPS makes the whole module cleaner, but you should be able to use it with the fallback just fine.
*Now* it should work for your situation and your players.  
Let me know if I managed to make it usable. (also no need to rush :) )

**Comment by JadeiteWren** [comment] 2022-04-14 03:15
The fallback with the pop-up works and is usable. Sucks that it has to do that, but I appreciate the fix and work around! Thank you so much!

**Closed as completed** 2022-04-14 10:56 UTC
