### ISSUE TITLE
No difference between Compendium & Items ? 

### ISSUE THREAD

**Issue by Steelskinz** [MisterIXI/fvtt-copy-id#4] opened 2022-07-06 07:49 UTC
Wich is a little problematic when the item is in a compendium and not in a world.
![image](https://user-images.githubusercontent.com/93941729/177498067-14d93d95-e00c-4eb9-a73d-2172505d6d97.png)

**Comment by MisterIXI** [comment] 2022-07-06 12:38
Ah yeah, I didn't notice it until now. At least the ID is already correct, but I'll have to see how to check for a compendium entry. 

This also happens for Actors and probably everything else related to Compendium entries. I'll see what I can do to fix it.

**Comment by MisterIXI** [comment] 2022-07-09 20:51
Well, interesting if that's how git works. I didn't intend on closing this already.
Now the update for a v1.1.2 is published. Please check if it works as intended :)

**Closed as completed** 2022-08-21 23:07 UTC
